#!/usr/bin/env bash
# script to install nginx on your web-01 server
apt-get update -y
apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx -t
service nginx restart
