#!/usr/bin/env bash
# script to install nginx on your web-01 server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
