#!/usr/bin/env bash
# bash script that echos into var/run, traps and runs infinite loop
echo $$ >> /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command && rm /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
while :
	do
		echo "To infinity and beyond"
		sleep 2
	done
