#!/usr/bin/env bash
# bash script that displays the time for 12 hrs and 59 mins
hours=0
while [ $hours -le 12 ];
do
	echo "Hour: $hours"
	min=1
	while [ $min -le 59 ];
	do
		echo "$min"
		((min++))
	done
	((hours++))
done
